# Generated by Django 2.0 on 2019-08-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190727_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='training_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
